### ISSUE TITLE
mouse over target - classic era

### ISSUE THREAD

**Issue by ikswezclam** [neotron/WoW-MagicMarker#23]
Hi, I am playing classic era (Vanilla). I was using your addon in past (TBC) and I remember I was able to mark mobs just by mouse over them right now in classic era I have to target mob to be able to mark him. Am I doing something wrong or is this option not available in classic era?

**Comment by liddqd** [comment]
Hi, sorry to butt in on this ticket. But it seems like development has staggered -and I am seemingly having a hard time to find any information regarding this addon and Era. 

I can't even get it to populate the database in the first place. I've tried different dungeons and raids. Are you able to do this?

Fwiw you can bind the "smart" key, which defaults to Alt under /magic config
