### ISSUE TITLE
[Classic TBCC] Tank marks don't reset after combat

### ISSUE THREAD

**Issue by tstirrat** [neotron/WoW-MagicMarker#6]
MM doesn't seem to detect the exit of combat. So the marks keep cycling to the next tank mark even after you've finished with an entire pack and dropped combat. I need to reset all marks every time and it's getting tedious.

e.g.

Mark skull, x, square using the "mark selected target" key. Kill mobs. Exit combat.

Next time you press the "mark selected target" key, it will use moon, triangle etc (whatever is next in your tank marks order)

**Comment by neotron** [comment]
The marks are cleared when the enemy dies - it doesn't have anything to do with leaving combat.

However it only tracks events when event handling is enabled. This should be automatic in instances (unless disabled), but doesn't in the wild even if the marking key works. 

Could this be the issue?

**Comment by tstirrat** [comment]
I haven't changed any settings since upgrading from classic to TBCC and this is happening inside instances (5 mans), so I think something is amiss. Let me know if there's anything other info I can provide to help debug!

**Comment by tstirrat** [comment]
I've been paying more attention to this, it works sometimes, and then other times it gets in a weird state. It worked in ZG and UBRS, but not Strat Live. I'll keep trying to figure out a reproducible situation.

**Comment by tstirrat** [comment]
Following up on this. It happens when I mark a mob and it doesn't die (i.e. it pats off into the distance etc). So this is not a bug. Thanks for your explanation :)
